### PR TITLE
feat: add missing parameters, docs, alignment with resource docs

### LINKED ISSUE #54: [AVM Module Issue]: AGW and Subnet in different resource group
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

v0.1.1

### (Optional) Correlation Id

_No response_

### Description

Dear module owner,

A nice feature would be if it is possible to deploy the gateway in a different resource group than the resource group where the subnet is deployed. Right now they must to be in same rg..

### LINKED ISSUE #59: [AVM Module Issue]: probe_configuration
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

I'm not sure

### (Optional) Module Version

0.1.1

### (Optional) Correlation Id

_No response_

### Description

In probe_configurations, match definition is not applied. Therefore probe changes are proposed in every apply.

### LINKED ISSUE #66: [AVM Module Issue]: Missing rewrite_rule_set block for creating rules
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

v0.1.1

### (Optional) Correlation Id

_No response_

### Description

@mofaizal

Would also like to see a rewrite_rule_set block for creating rules.

Ex.
````
## Rewrite rules
dynamic "rewrite_rule_set" {
  for_each = var.rewrite_rule_set

  content {
    name = rewrite_rule_set.value.name

    dynamic "rewrite_rule" {
      for_each = rewrite_rule_set.value.rewrite_rules != null ? rewrite_rule_set.value.rewrite_rules : {}

      content {
        name          = rewrite_rule.value.name
        rule_sequence = rewrite_rule.value.rule_sequence

        dynamic "condition" {
          for_each = lookup(rewrite_rule_set.value, "condition", [])
          content {
            variable    = condition.value.variable
            pattern     = condition.value.pattern
            ignore_case = condition.value.ignore_case
            negate      = condition.value.negate
          }
        }

        dynamic "request_header_configuration" {
          for_each = lookup(rewrite_rule.value, "request_header_configuration", [])
          content {
            header_name  = request_header_configuration.value.header_name
            header_value = request_header_configuration.value.header_value
          }
        }

        dynamic "response_header_configuration" {
          for_each = lookup(rewrite_rule.value, "response_header_configuration", [])
          content {
            header_name  = response_header_configuration.value.header_name
            header_value = response_header_configuration.value.header_value
          }
        }

        dynamic "url" {
          for_each = lookup(rewrite_rule.value, "url", [])
          content {
            path         = url.value.path
            query_string = url.value.query_string
            reroute      = url.value.reroute
          }
        }
      }
    }
  }
}
````

## Variable
````
variable "rewrite_rule_set" {
  description = "List of rewrite rule set"
  type        = any
  default     = []
}
````

## Input
````
rewrite_rule_set = [
  {
    name = "XFF-Headers"

    rewrite_rules = {
      rule_1 = {
        name          = "x-forwarded-for"
        rule_sequence = 102
        request_header_configuration = [
          {
            header_name  = "X-Forwarded-For"
            header_value = "{var_client_ip}"
          }
        ]
      }
    }
  }
]
````

### LINKED ISSUE #67: [AVM Module Issue]: AVM specification alignment, public IP resource should not be present in the main module?
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### (Optional) Correlation Id

_No response_

### Description

The AVM specification states that resources should only contain resources that are relevant to the resource provider scope and their sub resources

With this in mind, I believe the public IP address resource should be removed.

It is also adviseable to avoid unnecessary data objects.  I would recommend removing the subnet data block and instead supplying a subnet ID, which co-incidentally allows for subnets in different resource groups as well.

### LINKED ISSUE #68: [AVM Module Issue]: identity_ids should be managed_identities
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### (Optional) Correlation Id

_No response_

### Description

the share AVM specification requires managed identities to be specified as per this:

https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#managed-identities

### LINKED ISSUE #69: [AVM Module Issue]: many variable blocks are missing heredoc descriptions
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### (Optional) Correlation Id

_No response_

### Description

descriptions should use the heredoc format and include per parameter guidance, ref spec:

https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr1---category-documentation---descriptions

### LINKED ISSUE #70: [AVM Module Issue]: consumers of the module should be able to override naming conventions for FEIP/GWIP
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.0

### (Optional) Correlation Id

_No response_

### Description

The front end IP configuration name & gateway IP configuration name is inferred from the ``name`` variable and the format cannot be overridden by a module consumer - spec reference:

https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-snfr25---category-composition---resource-naming

### LINKED ISSUE #72: [AVM Module Issue]: the ``enable_https`` variable misses some scenarios (e.g. tcp)
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

_No response_

### (Optional) Correlation Id

_No response_

### Description

The backend pool summarises the port & protocol choices into a single variable ``enable_https``.  This is a nice helper, but it excludes certain choices, such as tcp for backend services that do not use http.

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-components#protocols

I recommend retaining the original parameters, port & protocol.

### PR DESCRIPTION
**Pull request by kewalaka**
## Description

This introduces the following:

### Breaking changes

- Introduction of front end ip configuration & gateway configuration, to allow for these resources to be named by the customer and also support scenarios such as private link.  This also removes the logic around private & public front ends - the same block serves both.  Fixes #70 

- Gateway configuration now takes a subnet_id removing the data block and allowing for different resource group - fixes #54.  I thought about having just a 'subnet_id' variable - but you need a gateway configuration block anyway to satisfy the above point (naming), so I think on balance it is better to make it more like the AzureRM interface.

- Managed identities interface now aligns to spec fixes #68

- Removes public IP from module to align with spec, fixes #67

- Modified the simplified "enable_https" approach to use port & protocol instead - this fixes it to work with custom protocols such as tcp.  Fixes #72 & #55 

- I believe the WAF configuration block should not be specified if you're using an external WAF policy (as all the examples that test WAF do already). Knowing this makes the ``enable_classic_rule`` flag redundant, if you do want to use classic WAF you just include a ``waf_configuration`` block.  We should (and currently do) promote the external WAF option, I would even argue for the classic WAF removal from the module interface, noting the flag to force an external WAF policy is already hard coded to true.

### Other changes

- I have merged this with the output of [newres](https://github.com/lonegunmanb/newres), which should fix missing parameters.

- Variables descriptions fixes #69 

- Add rewrite rule block fixes #66 

- Add match definition for probe configuration fixes #59 

- Fixes from grept-apply, included correct license copyright 

- Fixes from pre-commit/pr-check make targets

- Example updates to align with the above.  I've re-introduced a 'default' example, because grept expects it, moving the simplest of the existing ones into this folder.

I've checked these run to plan but need to complete E2E testing, sharing so that others can contribute.

-->

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [X] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [X] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [X] Breaking changes.
  - [X] Update to documentation

# Checklist

- [X] I'm sure there are no other open Pull Requests for the same update/change
- [ ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by kewalaka** [comment]
@mofaizal can we get a pr branch created please to help with running the integration tests, rather than me target main?

@matt-FFFFFF there's quite a bit of change here, the module needs some work to align to AVM.  I've tried to limit the core changes as much as possible, but the flow on into examples, plus changes from linting etc, adds up to quite a large changeset.

**Comment by kewalaka** [comment]
just done some apply testing on default & kv_selfssl_waf_https_app_gateway, evidence on the latter:

image

**Comment by mofaizal** [comment]
will create branch and test before merge to main. i will create branch update you the status.

**Comment by kewalaka** [comment]
i see the new branch - i'll raise an updated PR that re-establishes the PIP against version-0.2.0

**Pull request closed without merging**
